name: Terraform Manual Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      TF_VAR_docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      TF_VAR_docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init
      working-directory: infra

    - name: Terraform Plan
      run: terraform plan
      working-directory: infra

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: infra

    - name: Restart Azure Web App
      run: |
        az webapp restart \
          --name "${{ env.AZURE_WEBAPP_NAME }}" \
          --resource-group "${{ env.AZURE_RESOURCE_GROUP }}"
      env:
        AZURE_WEBAPP_NAME: ${{ env.TF_VAR_project_name }}-webapp
        AZURE_RESOURCE_GROUP: ${{ env.TF_VAR_resource_group_name }}
